### PR TITLE
add: token types

### PR DESCRIPTION
**Pull request by Eomm**
Related to: https://github.com/verdaccio/verdaccio/pull/1271

### CODE REVIEW

**Comment by juanpicado** [comment]
@Eomm could yo also update Typescript types?

**Comment by juanpicado** [comment]
@Eomm something else I forgot to mention (I could do it squashing but I'd rob you a commit) https://www.conventionalcommits.org/en/v1.0.0-beta.4/#commit-message-with-description-and-breaking-change-in-body

This a breaking change, so, we need this to jump from v5 to v6.

**Comment by Eomm** [comment]
> I could do it squashing but I'd rob you a commit

Would you like to fix the messages instead of squash? - I will do it in case-
I'm a great supporter of squash 😃

> This a breaking change, so, we need this to jump from v5 to v6.

Clear, should I release it or bump the version in this PR?

**Comment by juanpicado** [comment]
I'll squash then :-) Thanks @Eomm I'll publish them soon

**Comment by juanpicado** [comment]
@Eomm https://github.com/verdaccio/flow-types/releases/tag/v6.0.0

**Pull request merged**
